env: local

grpc:
  host: localhost
  port: 50051
  operation_timeout: 3s
  shutdown_timeout: 15s
  load_concurrent: 3
  read_concurrent: 3
  idle_ttl: 10m
  grpc_stream_buf_size: 32768
  max_limit: 1000
  default_limit: 100
  max_offset: 100
  default_offset: 10

postgres:
  host: localhost
  port: 5432
  user: root
  password: 1234
  database: root
  timeout: 3s
  max_retries: 3
  base_backoff: 3s
  max_connections: 10
  min_connections: 5

minio:
  host: localhost
  port: 9000
  bucket_name: images
  user: admin
  password: admin_password
  timeout: 3s
  max_retries: 3
  base_backoff: 3s